<a href="https://colab.research.google.com/github/Voltaire01-W/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Copy_of_LS_DS_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
##### Begin Working Here #####
import pandas as pd
import numpy as np

In [2]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-03-11 12:43:29--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [                 <=>]  21.71M   914KB/s    in 25s

2020-03-11 12:43:54 (906 KB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22763850]

In [3]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [4]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 60 months"," 16.14%","243.93","C","C4","Sale Consultant","2 years","RENT","90000","Not Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","079xx","NJ","8.8","0","Mar-1991","1","","43","11","1","10582","58.5%","32","w","0.00","0.00","10661.0577272374","10661.06","10000.00","661.06","0.0","0.0","0.0","May-2019","9698.79","","Dec-2019","0","","1","Individual","","","","0","0","15470","1","1","0","1","18","4888","65","1","3","2969","60","18100","2","0","2","4","1719","4906","67.3","0","0","133","333","2","2","1","2","","1","","0","4","6","5","15","6","8","23","6","11","0","0","0","1","100","80","1","0","25600","15470","15000","7500","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","6500","6500","6500"," 36 months"," 11.80%","215.28","B","B4","Educator ","2 years","RENT","46500","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","352xx","AL","21.01","0","Aug-2011","1","61","","24","0","6741","41.6%","30","w","4411.89","4411.89","2792.25","2792.25","2088.11","704.14","0.0","0.0","0.0","Feb-2020","0.0","Mar-2020","Jan-2020","0","61","1","Individual","","","","0","0","40223","4","12","2","2","5","33482","97","7","12","3662","79","16200","2","0","4","14","1749","7694","42.2","0","0","88","72","1","1","0","3","","5","61","2","6","10","6","6","14","11","16","10","24","0","0","0","9","93.3","0","0","0","50845","40223","13300","34645","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4500","4500","4500"," 36 months"," 11.31%","147.99","B","B3","Accounts Examiner III","10+ years","RENT","38500","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","786xx","TX","4.64","0","Dec-2003","0","25","","12","0","4472","15.3%","25","w","0.00","0.00","4549.2171485504","4549.22","4500.00","49.22","0.0","0.0","0.0","Feb-2019","4553.46","","Feb-2020","0","25","1","Individual","","","","0","306","29137","2","1","1","1","3","24665","100","3","7","3612","54","29200","0","3","3","8","2428","10735","28.9","0","0","180","69","2","2","0","2","","6","","1","3","5","5","6","10","11","15","5","12","0","0","0","4","91.7","0","0","0","53795","29137","15100","24595","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","25000","25000","25000"," 60 months"," 14.47%","587.82","C","C2","teacher","10+ years","OWN","110000","Not Verified","Dec-2018","Late (31-120 days)","n","","","credit_card","Credit card refinancing","117xx","NY","26.43","1","Jan-1997","0","7","","23","0","39053","45.7%","49","w","21975.89","21975.89","5848.05","5848.05","3024.11","2823.94","0.0","0.0","0.0","Oct-2019","587.82","Mar-2020","Jan-2020","0","7","1","Individual","","","","0","0","95648","0","3","0","0","35","54716","23","1","2","8422","39","85500","0","1","0","2","4159","34837","44.5","0","0","263","246","10","10","0","48","","","","0","9","13","10","14","21","19","27","13","23","0","0","1","1","98","10","0","0","179321","95648","62800","91424","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 27.27%","920.91","E","E5","Claims Analyst","1 year","RENT","50000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","857xx","AZ","23.62","0","Dec-1997","1","","","10","0","1258","10.7%","16","w","26429.58","26429.58","11903.65","11903.65","3570.42","8333.23","0.0","0.0","0.0","Feb-2020","0.0","Mar-2020","Jan-2020","0","","1","Individual","","","","0","0","27364","1","4","1","2","6","26106","76","0","1","1258","59","11800","2","0","1","3","2736","8842","12.5","0","0","84","252","16","6","0","16","","6","","0","1","1","4","4","7","6","9","1","10","0","0","0","1","100","0","0","0","46300","27364","10100","34500","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.14%","352.27","C","C4","Training Manager","10+ years","MORTGAGE","94800","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","325xx","FL","28.59","0","Jan-2009","1","","","18","0","49976","65.8%","37","w","6928.87","6928.87","4566.06","4566.06","3071.13","1494.93","0.0","0.0","0.0","Feb-2020","0.0","Mar-2020","Jan-2020","0","","1","Individual","","","","0","0","361716","1","6","2","4","6","45778","64","0","1","8297","65","75900","1","15","4","6","20095","12249","49.2","0","0","107","119","15","6","4","36","","0","","0","2","8","3","7","16","11","17","8","18","0","0","0","3","100","33.3","0","0","415969","95754","24100","71489","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","25000","25000","25000"," 60 months"," 12.98%","568.58","B","B5","Tire builder","10+ years","MORTGAGE","85000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","356xx","AL","36.67","1","Oct-1993","1","10","","14","0","26630","53.3%","27","w","20862.06","20862.06","7364.5","7364.50","4137.94","3226.56","0.0","0.0","0.0","Feb-2020","0.0","Mar-2020","Jan-2020","0","40","1","Joint App","140000","23.08","Not Verified","0","56","206980","1","7","1","3","3","69513","81","1","1","17292","68","50000","1","3","1","4","14784","18581","57.7","0","0","186","185","9","3","4","9","10","3","10","1","4","5","4","5","13","6","10","5","14","0","0","0","2","85.2","0","0","0","275691","96143","43900","99691","48711","Oct-1993","1","4","16","56.5","8","12","0","0","49","N","","","","","","","","","","","","","","","N","","","","","",""
"","","3000","3000","3000"," 36 months"," 10.33%","97.27","B","B1","Driver","7 years","RENT","40000","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","493xx","MI","10.68","0","Oct-2014","1","","67","3","1","3092","44.2%","5","w","1721.70","1721.70","1561.93","1561.93","1278.30","283.63","0.0","0.0","0.0","Feb-2020","0.0","Mar-2020","Jan-2020","0","","1","Individual","","","","0","0","12563","2","1","2","3","4","9471","95","0","0","3049","74","7000","4","2","2","3","4188","3908","44.2","0","0","13","50","46","4","0","46","","0","","0","2","2","2","2","3","2","2","2","3","0","0","0","2","100","0","1","0","17000","12563","7000","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [5]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","3387.58","3387.58","3032.81","3032.81","2212.42","820.39","0.0","0.0","0.0","Feb-2020","190.21","Mar-2020","Jan-2020","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","6101.42","6101.42","5539.82","5539.82","3898.58","1641.24","0.0","0.0","0.0","Feb-2020","346.76","Mar-2020","Jan-2020","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3024.63","3024.63","2713.51","2713.51","1975.37","738.14","0.0","0.0","0.0","Feb-2020","169.83","Mar-2020","Jan-2020","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","5959.76","5810.77","5227.52","5096.83","4040.24","1187.28","0.0","0.0","0.0","Feb-2020","327.68","Mar-2020","Jan-2020","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","6168.49","6168.49","5687.89","5687.89","3831.51","1856.38","0.0","0.0","0.0","Feb-2020","356.08","Mar-2020","Jan-2020","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2048833825
Total amount funded in policy code 2: 819375497

In [6]:
df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1)

print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128286, 144)

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                    NaN              NaN
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [7]:
df = df.drop(['url', 'member_id', 'desc', 'id'], axis=1)

df.head()

   loan_amnt  funded_amnt  ...  settlement_percentage settlement_term
0    10000.0      10000.0  ...                    NaN             NaN
1     6500.0       6500.0  ...                    NaN             NaN
2     4500.0       4500.0  ...                    NaN             NaN
3    25000.0      25000.0  ...                    NaN             NaN
4    30000.0      30000.0  ...                    NaN             NaN

[5 rows x 140 columns]

In [8]:
df['term'].head(10)

0     60 months
1     36 months
2     36 months
3     60 months
4     60 months
5     36 months
6     60 months
7     36 months
8     36 months
9     36 months
Name: term, dtype: object

In [0]:
term = ' 60 months'

In [10]:
term = term.strip().strip(' months')
term

'60'

In [11]:
term = int(term.strip().strip('months'))
term

60

In [12]:
df['term'].fillna('0 months', inplace=True)
print(df['term'].isna().sum())
df['term'] = df['term'].str.strip('months').astype(int)
print(type(df['term']))
df['term'].head()

0
<class 'pandas.core.series.Series'>

0    60
1    36
2    36
3    60
4    60
Name: term, dtype: int64

In [16]:
[col for col in df if col.endswith('_d')]

['issue_d', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d']

In [23]:
df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], infer_datetime_format=True)

df.dtypes[15:50]

pymnt_plan                             object
purpose                                object
title                                  object
zip_code                               object
addr_state                             object
dti                                   float64
delinq_2yrs                           float64
earliest_cr_line                       object
inq_last_6mths                        float64
mths_since_last_delinq                float64
mths_since_last_record                float64
open_acc                              float64
pub_rec                               float64
revol_bal                             float64
revol_util                             object
total_acc                             float64
initial_list_status                    object
out_prncp                             float64
out_prncp_inv                         float64
total_pymnt                           float64
total_pymnt_inv                       float64
total_rec_prncp                       float64
total_rec_int                         float64
total_rec_late_fee                    float64
recoveries                            float64
collection_recovery_fee               float64
last_pymnt_d                   datetime64[ns]
last_pymnt_amnt                       float64
next_pymnt_d                           object
last_credit_pull_d                     object
collections_12_mths_ex_med            float64
mths_since_last_major_derog           float64
policy_code                           float64
application_type                       object
annual_inc_joint                      float64
dtype: object

In [24]:
df['last_pymnt_d'].dt.year

0         2019.0
1         2020.0
2         2019.0
3         2019.0
4         2020.0
           ...
128281    2020.0
128282    2020.0
128283    2020.0
128284       NaN
128285       NaN
Name: last_pymnt_d, Length: 128286, dtype: float64

In [0]:
df['last_pymnt_d_year'] = df['last_pymnt_d'].dt.year
df['last_pymnt_d_month'] = df['last_pymnt_d'].dt.month

In [26]:
df.head()

   loan_amnt  funded_amnt  ...  last_pymnt_d_year  last_pymnt_d_month
0    10000.0      10000.0  ...             2019.0                 5.0
1     6500.0       6500.0  ...             2020.0                 2.0
2     4500.0       4500.0  ...             2019.0                 2.0
3    25000.0      25000.0  ...             2019.0                10.0
4    30000.0      30000.0  ...             2020.0                 2.0

[5 rows x 142 columns]

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01